[build]
publish = "."
functions = "netlify/functions"
command = "echo 'Application de surveillance des navires prête pour le déploiement'"

[build.environment]
NODE_VERSION = "18"

# Headers de sécurité
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' unpkg.com; style-src 'self' 'unsafe-inline' unpkg.com; img-src 'self' data: *.openstreetmap.org *.tile.openstreetmap.org; connect-src 'self' *.eurisportal.eu; font-src 'self' data:;"

# Headers pour les fonctions
[[headers]]
for = "/.netlify/functions/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Headers = "Content-Type, Authorization"
Access-Control-Allow-Methods = "GET, POST, OPTIONS"
Cache-Control = "no-cache, no-store, must-revalidate"

# Redirections
[[redirects]]
from = "/euris_proxy.php"
to = "/.netlify/functions/euris-proxy"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
