[build]
publish = "."
functions = "netlify/functions"
command = "echo 'Application de surveillance des navires prête pour le déploiement'"

[build.environment]
NODE_VERSION = "18"

# Configuration des fonctions
[functions]
node_bundler = "esbuild"

# Headers de sécurité pour l'application principale
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' unpkg.com cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' unpkg.com; img-src 'self' data: *.openstreetmap.org *.tile.openstreetmap.org; connect-src 'self' *.eurisportal.eu; font-src 'self' data:;"

# Headers spécifiques pour les fonctions Netlify
[[headers]]
for = "/.netlify/functions/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Headers = "Content-Type, Authorization"
Access-Control-Allow-Methods = "GET, POST, OPTIONS"
Cache-Control = "no-cache, no-store, must-revalidate"
Pragma = "no-cache"
Expires = "0"

# Headers pour les fichiers statiques
[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.css"
[headers.values]
Cache-Control = "public, max-age=31536000"

# Redirections pour compatibilité
[[redirects]]
from = "/euris_proxy.php"
to = "/.netlify/functions/euris-proxy"
status = 301
force = true

[[redirects]]
from = "/api/euris"
to = "/.netlify/functions/euris-proxy"
status = 301
force = true

# Fallback pour SPA (Single Page Application)
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
conditions = {Role = ["admin", "user"], Country = ["!US"]}

# Configuration pour le développement local
[dev]
framework = "#static"
command = "echo 'Démarrage du serveur de développement'"
targetPort = 8888
port = 8888
publish = "."
autoLaunch = true